### ISSUE TITLE
Better plugin info

### ISSUE THREAD

**Issue by pranavdeshai** [mrjackphil/obsidian-text-expand#4] opened 2020-11-10 15:19 UTC
This plugin proved to be a very handy tool for me, been using it a lot.

The templates feature in the plugin are really useful

However, I think the plugin info needs some more info and instructions on how to use these template features.

Thanks in advance.

**Comment by mrjackphil** [comment] 2020-11-10 16:03
@pranavdeshai23 Can you explain how it can be improved? I'm not experienced enough with documentation creation, so it could be useful to hear what problems you faced.

**Comment by mrjackphil** [comment] 2020-11-10 18:38
Try latest release 0.5.1, should fix some issues.

**Comment by mrjackphil** [comment] 2020-11-12 17:15
I just updated README. Is it more clear now how to use template feature?

**Comment by pranavdeshai23** [comment] 2020-11-12 18:03
> I just updated README. Is it more clear now how to use the template feature?

Cool. Thanks a lot for the update, really a huge time-saver for me. The README is clear now. My inability to understand the instructions before is probably also because of the plugin not working before, but it is working fine now.
However, just wanted to know what the number replacing the `$created` indicates?
Really looking forward to future updates and other plugins.

**Comment by autonomygaps** [comment] 2020-11-21 11:37
I think that part of the problem is the **name** of the plug-in.
If it were `Paste search results for {{text}} as links` it would be MUCH clearer. 
The current name reminds me of TextExpander, which is for abbreviations for snippets of text.

**Comment by mrjackphil** [comment] 2020-11-21 12:00
@autonomygaps But it's misleading because it's just one of the functionality. You can build a table with only file content without links, as example.

**Comment by mrjackphil** [comment] 2022-06-17 13:08
I'm closing this issue. Feel free to reopen this one or create another more specific issue.

**Closed by mrjackphil** 2022-06-17 13:08 UTC
Labels: documentation
