### ISSUE TITLE
query but no result returns

### ISSUE THREAD

**Issue by qwepuorytgj** [mrjackphil/obsidian-text-expand#93] opened 2024-02-15 03:41 UTC
![image](https://github.com/mrjackphil/obsidian-text-expand/assets/114298602/683336a0-2b19-4d15-8ea0-d8d2019b0fda)

after clicking `run expand query`, there is no response

the query results show in the search box but do not return to the note.

![image](https://github.com/mrjackphil/obsidian-text-expand/assets/114298602/9515d8ec-e598-4340-9347-d8d9cc7d4927)

**Comment by mrjackphil** [comment] 2024-02-15 05:29
It might be related to this issue #72
Just in case of testing try to move your search panel to the left side and try again to be sure what that's the issue.

**Comment by qwepuorytgj** [comment] 2024-02-15 06:03
> It might be related to this issue #72 Just in case of testing try to move your search panel to the left side and try again to be sure what that's the issue.

Yes, it works now. I moved the search panel to the left side.
Thank you very much.

> It might be related to this issue #72 Just in case of testing try to move your search panel to the left side and try again to be sure what that's the issue.

**Comment by mrjackphil** [comment] 2024-02-15 06:25
If you don't mind I'll close this issue as duplicate of #72

**Closed by mrjackphil** 2024-02-15 06:25 UTC
